In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

# a) Addition of 2 to all elements
arr_addition = arr + 2

# b) Multiply all elements by 3
arr_multiplication = arr * 3

# c) Divide every element by 2
arr_division = arr / 2

print("Original Array:", arr)
print("After Addition of 2:", arr_addition)
print("After Multiplication by 3:", arr_multiplication)
print("After Division by 2:", arr_division)


Original Array: [1 2 3 4 5]
After Addition of 2: [3 4 5 6 7]
After Multiplication by 3: [ 3  6  9 12 15]
After Division by 2: [0.5 1.  1.5 2.  2.5]


In [3]:
import numpy as np

# (a) Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed Array:", arr[::-1])

# (b) Find the most frequent value and its indices
def most_frequent(arr):
    unique, counts = np.unique(arr, return_counts=True)
    max_count = max(counts)
    most_common = unique[counts == max_count][0]
    indices = np.where(arr == most_common)[0]
    return most_common, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

val_x, idx_x = most_frequent(x)
val_y, idx_y = most_frequent(y)

print("\nArray x: Most Frequent Value:", val_x, "Indices:", idx_x)
print("Array y: Most Frequent Value:", val_y, "Indices:", idx_y)


Reversed Array: [5 4 6 3 2 1]

Array x: Most Frequent Value: 1 Indices: [0 5 7 8 9]
Array y: Most Frequent Value: 1 Indices: [0 1 2]


In [4]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
a = arr[0, 1]  # 1st row (index 0), 2nd column (index 1)
b = arr[2, 0]  # 3rd row (index 2), 1st column (index 0)

print("Element at 1st row, 2nd column:", a)
print("Element at 3rd row, 1st column:", b)


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [6]:
import numpy as np
arr = np.linspace(10, 100, 25)
print("Array:", arr)
print("Shape:", arr.shape)
print("Total elements:", arr.size)
print("Data type:", arr.dtype)
print("Total bytes used:", arr.nbytes)

# Transpose using reshape()
arr_reshaped = arr.reshape(25, 1)
print("\nTranspose using reshape():\n", arr_reshaped)

# Transpose using T
arr_T = arr.T
print("\nTranspose using T:\n", arr_T)
print("\nDoes T change a 1D array?", arr_T.shape == arr.shape)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes used: 200

Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Does T change a 1D array? True


In [9]:
import numpy as np
ucs420_kavu = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])
print("Mean:", np.mean(ucs420_kavu ))
print("Median:", np.median(ucs420_kavu ))
print("Max:", np.max(ucs420_kavu ))
print("Min:", np.min(ucs420_kavu ))
print("Unique elements:", np.unique(ucs420_kavu ))

# Reshape to 4 rows and 3 columns
reshaped_ucs420_kavu  = ucs420_kavu .reshape(4, 3)
print("\nReshaped (4x3) array:\n", reshaped_ucs420_kavu )

# Resize to 2 rows and 3 columns
resized_ucs420_kavu  = ucs420_kavu .reshape(2, 6)
print("\nResized (2x6) array:\n", resized_ucs420_kavu)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped (4x3) array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized (2x6) array:
 [[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
